version: '3.8'
services:
  backend:
    build: 
      dockerfile: Dockerfile
    container_name: book-backend
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "${API_PORT}:8000"
    networks:
      - db-network
  db:
    image: postgres:alpine
    container_name: book-db
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD} 
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5454:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - db-network
volumes:
  db-data:
networks:
  db-network:

